version: "3.9"  # optional since v1.27.0

services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    ports:
      - "9544:9544"

  dot-price:
    build:
      context: .
      dockerfile: ./docker/price/Dockerfile
    environment:
        currency: "DOT"
        start: 1597622400000

  ksm-price:
    build:
      context: .
      dockerfile: ./docker/price/Dockerfile
    environment:
        currency: "KSM"
        start: 1599177600000

  subscriber:
    build:
      context: .
      dockerfile: ./docker/subscriber/Dockerfile
    ports:
        - "9505:9505"

  scheduler:
    build:
      context: .
      dockerfile: ./docker/scheduler/Dockerfile

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password