definitions:
  auth.Address:
    properties:
      address:
        description: Blockchain address from account
        type: string
      pubKey:
        description: PubKey from account
        type: string
      sign:
        description: 'Sign for message (more information here: https://github.com/fractapp/fractapp-server/blob/main/AUTH.md)'
        type: string
    type: object
  auth.ConfirmAuthRq:
    properties:
      addresses:
        additionalProperties:
          $ref: '#/definitions/auth.Address'
        description: Addresses by network (0 - polkadot/ 1 - kusama) from account
        type: object
      code:
        description: The code that was sent
        type: string
      type:
        description: Message type with code (0 - sms / 1 - email)
        enum:
        - 0
        - 1
        type: integer
      value:
        description: Email address or Phone number (without +)
        type: string
    type: object
  auth.SendCodeRq:
    properties:
      checkType:
        description: Now it is always zero. But in future it will have more types.
        enum:
        - 0
        type: integer
      type:
        description: Message type (0 - sms / 1 - email)
        enum:
        - 0
        - 1
        type: integer
      value:
        description: Email address or Phone number (without +)
        type: string
    type: object
  auth.TokenRs:
    properties:
      token:
        description: JWT token
        type: string
    type: object
  notification.UpdateTokenRq:
    properties:
      address:
        description: Blockchain address
        type: string
      network:
        description: network id (0 - polkadot/ 1 - kusama) from address
        type: integer
      pubKey:
        description: Public key from address
        type: string
      sign:
        description: 'signature for message (more information here: https://github.com/fractapp/fractapp-server/blob/main/AUTH.md)'
        type: string
      timestamp:
        description: timestamp from message
        type: integer
      token:
        description: firebase token
        type: string
    type: object
  profile.MyProfile:
    properties:
      avatarExt:
        description: avatar format (png/jpg/jpeg)
        type: string
      email:
        type: string
      id:
        description: id from info
        type: string
      isMigratory:
        description: always false. This property is for the future
        type: boolean
      lastUpdate:
        description: timestamp of the last info update
        type: integer
      name:
        description: name in fractapp
        type: string
      phoneNumber:
        type: string
      username:
        description: username in fractapp
        type: string
    type: object
  profile.ShortUserProfile:
    properties:
      addresses:
        additionalProperties:
          type: string
        description: String addresses by network (0 - polkadot/ 1 - kusama) from account
        type: object
      avatarExt:
        description: avatar format (png/jpg/jpeg)
        type: string
      id:
        description: id from info
        type: string
      lastUpdate:
        description: timestamp of the last info update
        type: integer
      name:
        type: string
      username:
        type: string
    type: object
  profile.UpdateProfileRq:
    properties:
      name:
        type: string
      username:
        type: string
    type: object
info:
  contact:
    email: support@fractapp.com
    name: Support
  license:
    name: Apache 2.0
    url: https://github.com/fractapp/fractapp-server/blob/main/LICENSE
  termsOfService: https://fractapp.com/legal/tos.pdf
paths:
  /auth/sendCode:
    post:
      consumes:
      - application/json
      description: send auth code to email/phone
      operationId: send-auth-code
      parameters:
      - description: Send code rq
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/auth.SendCodeRq'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "202":
          description: Accepted
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: Send code
      tags:
      - Authorization
  /auth/signIn:
    post:
      consumes:
      - application/json
      description: sign in to fractapp account
      operationId: signIn
      parameters:
      - description: Confirm auth rq
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/auth.ConfirmAuthRq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.TokenRs'
        "400":
          description: Bad Request
          schema:
            type: string
        "403":
          description: Forbidden
          schema:
            type: string
        "429":
          description: Too Many Requests
          schema:
            type: string
      security:
      - AuthWithPubKey-SignTimestamp: []
      - AuthWithPubKey-Sign: []
      - AuthWithPubKey-Auth-Key: []
      summary: Sign in
      tags:
      - Authorization
  /notification/subscribe:
    post:
      consumes:
      - application/json
      description: subscribe for notifications about transaction
      operationId: subscribe
      parameters:
      - description: update token request
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/notification.UpdateTokenRq'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Subscribe
      tags:
      - Notification
  /profile/avatar/{userId}:
    get:
      consumes:
      - application/json
      operationId: avatar
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get user avatar
      tags:
      - Profile
  /profile/contacts:
    get:
      consumes:
      - application/json
      operationId: myContacts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - AuthWithJWT: []
      summary: Get my contacts
      tags:
      - Profile
  /profile/info:
    get:
      consumes:
      - application/json
      description: get user by id or blockchain address
      operationId: info
      parameters:
      - description: get user profile by user id
        in: query
        name: id
        type: string
      - description: get user profile by blockchain address
        in: query
        name: address
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/profile.ShortUserProfile'
        "400":
          description: Bad Request
          schema:
            type: string
      summary: Get user
      tags:
      - Profile
  /profile/matchContacts:
    get:
      consumes:
      - application/json
      description: Only those who are in your contacts can see your profile by phone
        number. Your number should also be in their contacts.
      operationId: myMatchContacts
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - AuthWithJWT: []
      summary: Get my matched contacts
      tags:
      - Profile
  /profile/my:
    get:
      consumes:
      - application/json
      operationId: myProfile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/profile.MyProfile'
        "400":
          description: ""
      security:
      - AuthWithJWT: []
      summary: Get my profile
      tags:
      - Profile
  /profile/search:
    get:
      consumes:
      - application/json
      description: search user by email or username
      operationId: search
      parameters:
      - description: username or email value
        in: query
        name: value
        required: true
        type: string
      - description: email/username
        in: query
        name: type
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/profile.ShortUserProfile'
            type: array
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: ""
      summary: Search user
      tags:
      - Profile
  /profile/updateProfile:
    post:
      consumes:
      - application/json
      operationId: updateProfile
      parameters:
      - description: update profile model
        in: body
        name: rq
        required: true
        schema:
          $ref: '#/definitions/profile.UpdateProfileRq'
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - AuthWithJWT: []
      summary: Update my profile
      tags:
      - Profile
  /profile/uploadAvatar:
    post:
      consumes:
      - application/x-www-form-urlencoded
      operationId: uploadAvatar
      parameters:
      - description: image/jpeg or image/jpg or image/png
        in: formData
        name: format
        required: true
        type: string
      - description: avatar in base64 (https://onlinepngtools.com/convert-png-to-base64)
        in: formData
        name: avatar
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - AuthWithJWT: []
      summary: Update avatar
      tags:
      - Profile
  /profile/uploadContacts:
    post:
      consumes:
      - application/json
      operationId: uploadMyContacts
      parameters:
      - description: phone numbers of contacts
        in: body
        name: rq
        required: true
        schema:
          items:
            type: string
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
      security:
      - AuthWithJWT: []
      summary: Upload my phone numbers of contacts
      tags:
      - Profile
  /profile/username:
    get:
      consumes:
      - application/json
      operationId: getTransactions
      parameters:
      - description: address
        in: query
        name: address
        required: true
        type: string
      - description: page
        in: query
        name: page
        required: true
        type: integer
      - description: size
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ""
        "400":
          description: Bad Request
          schema:
            type: string
        "404":
          description: Not Found
          schema:
            type: string
      summary: get transaction by address
      tags:
      - Profile
securityDefinitions:
  AuthWithJWT:
    in: header
    name: Authorization
    type: apiKey
  AuthWithPubKey-Auth-Key:
    in: header
    name: Auth-Key
    type: apiKey
  AuthWithPubKey-Sign:
    in: header
    name: Sign
    type: apiKey
  AuthWithPubKey-SignTimestamp:
    in: header
    name: Sign-Timestamp
    type: apiKey
swagger: "2.0"
